# Generated by packaging/homebrew/write-cask.sh in archways404/TVX-SOC-COAT; don't edit by hand.
cask "coat@preview" do
  version "1.1.0-preview.1"
  sha256 "1503dd748cecf05ee987d22e10571f2cb8ffe5645aa53a1b37f817ae90a5bc40"

  url "https://github.com/archways404/TVX-SOC-COAT/releases/download/v#{version}/COAT_v#{version}_PREVIEW.zip"
  name "COAT Preview"
  desc "Preview build of COAT: trace a phone call through simlog"
  homepage "https://github.com/archways404/TVX-SOC-COAT"

  # COAT updates itself, so `brew upgrade` leaves it alone unless you add --greedy.
  auto_updates true
  depends_on :macos

  app "COAT Preview.app"

  zap trash: [
    "~/Library/Application Support/COAT Preview",
    "~/Library/Preferences/se.telavox.coat.preview.plist",
  ]
end
