# Generated by packaging/homebrew/write-cask.sh in archways404/TVX-SOC-COAT; don't edit by hand.
cask "coat" do
  version "1.0.0"
  sha256 "e783732fee09167e5179917d6aa1788ac46da48ddd87f4adefdc96b88e077146"

  url "https://github.com/archways404/TVX-SOC-COAT/releases/download/v#{version}/COAT_v#{version}.zip"
  name "COAT"
  desc "Trace a phone call through simlog: its route, why each hop happened, problems"
  homepage "https://github.com/archways404/TVX-SOC-COAT"

  # COAT updates itself, so `brew upgrade` leaves it alone unless you add --greedy.
  auto_updates true
  depends_on :macos

  app "COAT.app"

  zap trash: [
    "~/Library/Application Support/COAT",
    "~/Library/Preferences/se.telavox.coat.plist",
  ]
end
