# Generated by packaging/homebrew/write-cask.sh in archways404/TVX-SOC-COAT; don't edit by hand.
cask "coat@preview" do
  version "0.5.0-preview.2"
  sha256 "48119da35a8ec489453b9095f8e69ee7355df74df707c703c43e3a45e2102148"

  url "https://github.com/archways404/TVX-SOC-COAT/releases/download/v#{version}/COAT_v#{version}_PREVIEW.zip"
  name "COAT Preview"
  desc "Preview build of COAT: trace a phone call through simlog"
  homepage "https://github.com/archways404/TVX-SOC-COAT"

  # COAT updates itself, so `brew upgrade` leaves it alone unless you add --greedy.
  auto_updates true
  depends_on :macos

  app "COAT Preview.app"

  zap trash: [
    "~/Library/Application Support/COAT Preview",
    "~/Library/Preferences/se.telavox.coat.preview.plist",
  ]
end
